<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class EquipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('equipment')->insert([
            [
                'nama_alat' => 'Alat Uji Ekstrak',
                'slug' => Str::slug('Alat Uji Ekstrak'),
                'keterangan_alat' => '<p>Alat uji ekstrak digunakan untuk menganalisis dan menentukan kadar zat tertentu dalam material, terutama aspal dan bahan lainnya yang digunakan dalam konstruksi.</p>',
                // 'gambar_alat' => '1. Uji ekstrak portrai.jpeg', // Dihapus karena menggunakan Spatie Media Library
                'facility_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Berat Jenis',
                'slug' => Str::slug('Alat Uji Berat Jenis'),
                'keterangan_alat' => '<p>peralatan pengujian Kepadatan canggih untuk mengukur sampel padat dan cair dengan sensor presisi tinggi dan fungsi penimbangan otomatis.</p>',
                // 'gambar_alat' => '2. Berat jenis coredrill aspal.jpeg',
                'facility_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Core Drill',
                'slug' => Str::slug('Alat Uji Core Drill'),
                'keterangan_alat' => '<p>mesin bor berbentuk silinder yang digunakan untuk mengambil sampel beton atau aspal dari struktur bangunan atau jalan. Sampel yang diambil berbentuk silinder dan kemudian dibawa ke laboratorium untuk diuji.</p>',
                // 'gambar_alat' => '2. Berat jenis coredrill aspal.jpeg',
                'facility_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Penetrasi',
                'slug' => Str::slug('Alat Uji Penetrasi'),
                'keterangan_alat' => '<p>perangkat atau metode yang digunakan untuk menguji seberapa jauh suatu benda, seperti jarum atau konus, dapat menembus suatu material, biasanya untuk mengukur kekerasan atau konsistensi material tersebut. </p>',
                // 'gambar_alat' => '4.Uji penetrasi aspal.jpeg',
                'facility_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Mix Design',
                'slug' => Str::slug('Alat Mix Design'),
                'keterangan_alat' => '<p>secara umum merujuk pada proses perancangan dan penentuan komposisi bahan-bahan yang akan digunakan dalam pembuatan beton (concrete mix design). Ini melibatkan penentuan proporsi yang tepat dari semen, air, agregat halus (pasir), dan agregat kasar (kerikil) untuk mencapai mutu beton yang diinginkan. </p>',
                // 'gambar_alat' => '5-7. Mix Design .jpeg',
                'facility_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Marshall Test',
                'slug' => Str::slug('Alat Marshall Test'),
                'keterangan_alat' => '<p>alat yang digunakan untuk menguji kekuatan dan kualitas campuran aspal dalam konstruksi jalan, khususnya perkerasan lentur. Alat ini mengukur stabilitas dan flow (kelelehan) campuran aspal ketika diberi beban. </p>',
                // 'gambar_alat' => '8. Marshall Test.jpeg',
                'facility_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Pengukur Debit Aliran',
                'slug' => Str::slug('Alat Pengukur Debit Aliran'),
                'keterangan_alat' => '<p>Alat pengukur debit aliran adalah flow meter. Flow meter digunakan untuk mengukur volume fluida (cairan atau gas) yang mengalir melalui suatu sistem atau pipa dalam satuan waktu tertentu. </p>',
                // 'gambar_alat' => '9. Pengukuran debit aliran.jpeg',
                'facility_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Tekan Material Analog',
                'slug' => Str::slug('Alat Uji Tekan Material Analog'),
                'keterangan_alat' => '<p>Alat uji tekan material analog adalah perangkat mekanis yang digunakan untuk menguji kekuatan tekan suatu material, seperti beton, batu bata, atau logam, dengan menggunakan sistem analog (tidak digital) untuk membaca tekanan yang diberikan. Alat ini biasanya terdiri dari piston, silinder, dan manometer analog untuk menunjukkan tekanan yang diberikan kepada sampel material. </p>',
                // 'gambar_alat' => '14. Uji tekan material analog.jpeg',
                'facility_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Tarik',
                'slug' => Str::slug('Alat Uji Tarik'),
                'keterangan_alat' => '<p>Alat uji tarik, juga dikenal sebagai Tensile Tester atau Tensile Strength Tester, adalah alat yang digunakan untuk menguji kekuatan tarik atau tegangan tarik suatu bahan. Alat ini bekerja dengan menarik sampel bahan hingga patah dan mencatat tegangan dan regangan yang terjadi, sehingga menghasilkan kurva uji tarik. </p>',
                // 'gambar_alat' => '15. Uji Tarik.jpeg',
                'facility_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Scan Rebar',
                'slug' => Str::slug('Alat Uji Scan Rebar'),
                'keterangan_alat' => '<p>Alat uji scan rebar adalah perangkat yang digunakan untuk mendeteksi dan mengukur lokasi, kedalaman, dan diameter tulangan baja (rebar) yang tertanam di dalam beton tanpa merusak struktur beton. Alat ini sering digunakan dalam inspeksi struktur bangunan untuk mengevaluasi kondisi rebar dan memastikan keamanan struktur.</p>',
                // 'gambar_alat' => '16. Uji Scan Rebar.jpeg',
                'facility_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Berat Jenis Kerikil',
                'slug' => Str::slug('Alat Uji Berat Jenis Kerikil'),
                'keterangan_alat' => '<p>Alat uji berat jenis kerikil (agregat kasar) meliputi timbangan dengan ketelitian 0,5 gram, keranjang besi, alat penggantung keranjang, oven, dan handuk/kain lap. Prosedur ini digunakan untuk menentukan berat volume kerikil dalam kondisi kering tusuk. </p>',
                // 'gambar_alat' => '17. Berat Jenis Kerikil.jpeg',
                'facility_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Berat Jenis Pasir',
                'slug' => Str::slug('Alat Uji Berat Jenis Pasir'),
                'keterangan_alat' => '<p>Alat utama yang digunakan untuk uji berat jenis pasir adalah piknometer dan timbangan. Piknometer digunakan untuk mengukur volume pasir dan air, sementara timbangan digunakan untuk mengukur berat pasir dan air. </p>',
                // 'gambar_alat' => '18. Uji berat jenis pasir.jpeg',
                'facility_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Gradasi',
                'slug' => Str::slug('Alat Uji Gradasi'),
                'keterangan_alat' => '<p>Alat uji gradasi adalah alat yang digunakan untuk menentukan distribusi ukuran butir (gradasi) dari bahan agregat, seperti pasir atau kerikil. Alat ini biasanya terdiri dari serangkaian saringan dengan ukuran lubang yang berbeda, yang digunakan untuk memisahkan agregat berdasarkan ukurannya. </p>',
                // 'gambar_alat' => '19,20,39 Gradasi.jpeg',
                'facility_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Abrasi',
                'slug' => Str::slug('Alat Uji Abrasi'),
                'keterangan_alat' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo suscipit aut ex, eaque recusandae tempore?</p>',
                // 'gambar_alat' => '22. Uji Abrasi.jpeg',
                'facility_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Lentur',
                'slug' => Str::slug('Alat Uji Lentur'),
                'keterangan_alat' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo suscipit aut ex, eaque recusandae tempore?</p>',
                // 'gambar_alat' => '25-26. Uji Lentur.jpeg',
                'facility_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Concrete Mixer',
                'slug' => Str::slug('Concrete Mixer'),
                'keterangan_alat' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo suscipit aut ex, eaque recusandae tempore?</p>',
                // 'gambar_alat' => '27. Mix Design beton Concrete Mixer.jpeg',
                'facility_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Tekan Digital',
                'slug' => Str::slug('Alat Uji Tekan Digital'),
                'keterangan_alat' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo suscipit aut ex, eaque recusandae tempore?</p>',
                // 'gambar_alat' => '28. uji tekan digital.jpg',
                'facility_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Berat Jenis Besi',
                'slug' => Str::slug('Alat Uji Berat Jenis Besi'),
                'keterangan_alat' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo suscipit aut ex, eaque recusandae tempore?</p>',
                // 'gambar_alat' => '33. Uji berat jenis besi.jpeg',
                'facility_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Hammer Test',
                'slug' => Str::slug('Alat Hammer Test'),
                'keterangan_alat' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo suscipit aut ex, eaque recusandae tempore?</p>',
                // 'gambar_alat' => '34. Hammer Test.jpeg',
                'facility_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Sondir',
                'slug' => Str::slug('Alat Sondir'),
                'keterangan_alat' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo suscipit aut ex, eaque recusandae tempore?</p>',
                // 'gambar_alat' => '35. Sondir.jpeg',
                'facility_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Bor Tangan',
                'slug' => Str::slug('Alat Uji Bor Tangan'),
                'keterangan_alat' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo suscipit aut ex, eaque recusandae tempore?</p>',
                // 'gambar_alat' => '36. Uji bor tangan.jpeg',
                'facility_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Pergeseran',
                'slug' => Str::slug('Alat Uji Pergeseran'),
                'keterangan_alat' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo suscipit aut ex, eaque recusandae tempore?</p>',
                // 'gambar_alat' => '41. Pengujian Geser langsung.jpeg',
                'facility_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji CBR',
                'slug' => Str::slug('Alat Uji CBR'),
                'keterangan_alat' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo suscipit aut ex, eaque recusandae tempore?</p>',
                // 'gambar_alat' => '44-45. CBR Lab..jpeg',
                'facility_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Sandcone Lapangan',
                'slug' => Str::slug('Alat Uji Sandcone Lapangan'),
                'keterangan_alat' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo suscipit aut ex, eaque recusandae tempore?</p>',
                // 'gambar_alat' => '46. Uji Sandcone lapanga.jpeg',
                'facility_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji CBR Lapangan',
                'slug' => Str::slug('Alat Uji CBR Lapangan'),
                'keterangan_alat' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo suscipit aut ex, eaque recusandae tempore?</p>',
                // 'gambar_alat' => '48. CBR Lapangan.jpeg',
                'facility_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji DCP',
                'slug' => Str::slug('Alat Uji DCP'),
                'keterangan_alat' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo suscipit aut ex, eaque recusandae tempore?</p>',
                // 'gambar_alat' => '49. UJI DCP.jpeg',
                'facility_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Alat Uji Pemetaan',
                'slug' => Str::slug('Alat Uji Pemetaan'),
                'keterangan_alat' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo suscipit aut ex, eaque recusandae tempore?</p>',
                // 'gambar_alat' => '54-60. uji pemetaa.jpeg',
                'facility_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            ]);
    }
}
