<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class TestingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('testings')->insert([
            // LT - Laboratorium Transportasi (facility_id: 1)
            [
                'nama_testing' => 'Uji Ekstraksi Aspal',
                'slug' => Str::slug('Uji Ekstraksi Aspal'),
                'keterangan' => '<p>Uji ekstraksi aspal adalah proses pemisahan aspal dari campuran perkerasan jalan atau bahan lain yang mengandung aspal menggunakan pelarut, untuk menentukan kadar aspal yang ada.</p>',
                'sampel' => '2',
                'satuan' => 'Sampel',
                'harga' => 250000,
                'catatan' => 'Minimal 2 sampel',
                // 'gambar' => '1. Uji ekstrak portrai.jpeg', // Ditangani Spatie Media Library
                'facility_id' => 1,
                'equipment_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Uji Berat Jenis Core Drill Aspal',
                'slug' => Str::slug('Uji Berat Jenis Core Drill Aspal'),
                'keterangan' => '<p>Berat jenis aspal merupakan hasil perbandingan antara berat aspal atau ter terhadap berat air suling dengajn isi yang sama pada suhu tertentu. Metode ini dilakukan untuk menentukan berat jenis atau kepadatan perkerasan aspal di lapangan</p>',
                'sampel' => '3',
                'satuan' => 'Sampel',
                'harga' => 100000,
                'catatan' => 'Minimal 3 sampel',
                // 'gambar' => '2. Berat jenis coredrill aspal.jpeg',
                'facility_id' => 1,
                'equipment_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Core Drill Aspal',
                'slug' => Str::slug('Core Drill Aspal'),
                'keterangan' => '<p>Core drill aspal adalah metode pengambilan sampel inti (core sampling) dari lapisan aspal dengan menggunakan mesin bor</p>',
                'sampel' => '5',
                'satuan' => 'Titik',
                'harga' => 200000,
                'catatan' => 'Minimal 5 titik (belum termasuk biaya survei, transport & akomodasi)',
                // 'gambar' => '3, 30. Core drill.jpeg',
                'facility_id' => 1,
                'equipment_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Penetrasi Aspal',
                'slug' => Str::slug('Penetrasi Aspal'),
                'keterangan' => '<p>Uji penetrasi aspal adalah metode untuk mengukur seberapa jauh jarum standar dapat menembus sampel aspal pada kondisi standar, seperti suhu 25°C, beban 50/100 gram, dan waktu 5 detik. Hasilnya, disebut nilai penetrasi, menunjukkan kekerasan aspal.</p>',
                'sampel' => '2',
                'satuan' => 'Sampel',
                'harga' => 250000,
                'catatan' => 'Minimal 2 sampel',
                // 'gambar' => '4. Uji penetrasi aspal.jpg',
                'facility_id' => 1,
                'equipment_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Mix Design Laston',
                'slug' => Str::slug('Mix Design Laston'),
                'keterangan' => '<p>Mix Design Laston adalah proses merancang dan menentukan proporsi atau perbandingan bahan-bahan dalam campuran aspal beton (Laston) yang akan digunakan pada konstruksi jalan, dengan tujuan untuk mencapai kualitas dan performa yang diinginkan. Mix Design ini melibatkan pemilihan material (agregat kasar, agregat halus, filler, dan aspal) serta penentuan proporsi masing-masing bahan tersebut. </p>',
                'sampel' => '1',
                'satuan' => 'Sampel',
                'harga' => 4500000,
                'catatan' => null,
                // 'gambar' => '5-7. Mix Design.jpeg',
                'facility_id' => 1,
                'equipment_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Mix Design Latasir',
                'slug' => Str::slug('Mix Design Latasir'),
                'keterangan' => '<p>Mix Design Latasir adalah proses menentukan perbandingan atau komposisi bahan-bahan yang akan digunakan dalam pembuatan lapis tipis aspal pasir (Latasir). Latasir adalah lapisan permukaan jalan yang terbuat dari campuran aspal dan pasir, yang biasanya dicampur dan dipanaskan secara bersamaan di lapangan. Tujuan Mix Design Latasir adalah untuk memastikan bahwa campuran tersebut memiliki kualitas dan kinerja yang optimal sesuai dengan kebutuhan jalan yang akan dibuat.</p>',
                'sampel' => '1',
                'satuan' => 'Sampel',
                'harga' => 2500000,
                'catatan' => null,
                // 'gambar' => '5-7. Mix Design.jpeg',
                'facility_id' => 1,
                'equipment_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Mix Design LPA',
                'slug' => Str::slug('Mix Design LPA'),
                'keterangan' => '<p>Mix Design LPA (Lapis Pondasi Agregat) adalah proses merancang campuran material untuk pondasi jalan yang menggunakan agregat (batu, kerikil, pasir) dengan berbagai fraksi. Tujuan utama adalah memastikan pondasi memiliki kekuatan dan stabilitas yang cukup untuk menahan beban lalu lintas.</p>',
                'sampel' => '1',
                'satuan' => 'Sampel',
                'harga' => 3500000,
                'catatan' => null,
                // 'gambar' => '5-7. Mix Design.jpeg',
                'facility_id' => 1,
                'equipment_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Uji Marshall',
                'slug' => Str::slug('Uji Marshall'),
                'keterangan' => '<p>Uji Marshall Aspal adalah metode standar untuk mengukur karakteristik fisik dan mekanik campuran aspal, seperti stabilitas dan kelelehan (flow). Uji ini digunakan untuk menentukan kualitas campuran aspal yang akan digunakan dalam konstruksi jalan, dengan mengukur kemampuan campuran untuk menahan beban dan deformasi. </p>',
                'sampel' => '2',
                'satuan' => 'Sampel',
                'harga' => 250000,
                'catatan' => 'Minimal 2 sampel',
                // 'gambar' => '8. Marshall Test.jpeg',
                'facility_id' => 1,
                'equipment_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // LH - Laboratorium Hidro (facility_id: 2)
            [
                'nama_testing' => 'Pengukuran Debit Saluran',
                'slug' => Str::slug('Pengukuran Debit Saluran'),
                'keterangan' => '<p>Pengukuran debit aliran air pada saluran/drainase. Ukuran debit air perlu diketahui sebagai dasar dalam analisis - analisis selanjutnya, terutama dalam analisis debit andalan, debit banjir, dan atau kepentingan analisis kualitas air.</p>',
                'sampel' => '3',
                'satuan' => 'Titik',
                'harga' => 300000,
                'catatan' => 'Minimal 3 titik (belum termasuk biaya survei, transport & akomodasi)',
                // 'gambar' => '9. Pengukuran debit aliran.jpeg',
                'facility_id' => 2,
                'equipment_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Pengukuran Bathimetri',
                'slug' => Str::slug('Pengukuran Bathimetri'),
                'keterangan' => '<p>Pengukuran batimetri adalah proses pengukuran kedalaman dan pemetaan topografi dasar perairan (laut, sungai, dan danau). Pengukuran ini menggunakan metode akustik seperti echosounder untuk menentukan kedalaman dan membuat peta kontur dasar laut. </p>',
                'sampel' => '1',
                'satuan' => 'Ha',
                'harga' => 1500000,
                'catatan' => 'Minimal 1 Ha (belum termasuk biaya survei, transport & akomodasi)',
                // 'gambar' => '',
                'facility_id' => 2,
                'equipment_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Pengukuran Sedimen Layang',
                'slug' => Str::slug('Pengukuran Sedimen Layang'),
                'keterangan' => '<p>Pengukuran sedimen layang (suspended sediment) melibatkan pengambilan sampel air yang mengandung sedimen, kemudian analisis laboratorium untuk menentukan konsentrasi dan ukuran partikel sedimen. Proses ini penting untuk memahami transportasi sedimen di sungai dan saluran air lainnya, serta untuk mengevaluasi kualitas air dan dampak sedimentasi. </p>',
                'sampel' => '3',
                'satuan' => 'Titik',
                'harga' => 300000,
                'catatan' => 'Minimal 3 titik (belum termasuk biaya survei, transport & akomodasi)',
                // 'gambar' => '',
                'facility_id' => 2,
                'equipment_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Pengukuran Sedimen Dasar',
                'slug' => Str::slug('Pengukuran Sedimen Dasar'),
                'keterangan' => '<p>Pengukuran sedimen dasar (bed load) adalah proses mengukur jumlah dan jenis sedimen yang bergerak di sepanjang dasar sungai atau saluran air. Metode ini penting untuk memahami dinamika sungai dan pengaruhnya terhadap lingkungan. Pengukuran dapat dilakukan secara langsung dengan mengambil sampel langsung dari sungai atau secara tidak langsung dengan menggunakan model hidrologi atau perhitungan berdasarkan faktor-faktor seperti debit aliran dan ukuran partikel sedimen. </p>',
                'sampel' => '3',
                'satuan' => 'Titik',
                'harga' => 300000,
                'catatan' => 'Minimal 3 titik (belum termasuk biaya survei, transport & akomodasi)',
                // 'gambar' => '',
                'facility_id' => 2,
                'equipment_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Uji Kualitas Air Pengecoran',
                'slug' => Str::slug('Uji Kualitas Air Pengecoran'),
                'keterangan' => '<p>Uji kualitas air dalam pengecoran penting untuk memastikan mutu beton yang baik. Air yang digunakan harus bersih, tidak mengandung bahan organik, bahan kimia berbahaya (seperti besi, sulfat, dan klorida), serta tidak mengandung minyak. Uji kualitas air ini sering dilakukan untuk memastikan air tidak mengandung zat yang dapat merusak atau mengurangi kekuatan beton. </p>',
                'sampel' => '1',
                'satuan' => 'Sampel',
                'harga' => 200000,
                'catatan' => null,
                // 'gambar' => '',
                'facility_id' => 2,
                'equipment_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // LSBB - Laboratorium Struktur & Bahan Bangunan (facility_id: 3)
            [
                'nama_testing' => 'Uji Tekan Material (Alat Analog)',
                'slug' => Str::slug('Uji Tekan Material (Alat Analog)'),
                'keterangan' => '<p>Uji tekan material menggunakan alat analog adalah metode pengujian destruktif yang digunakan untuk menentukan seberapa kuat suatu material saat diberikan tekanan yang terus meningkat. Alat analog dalam konteks ini adalah alat uji tekan manual, bukan alat digital atau otomatis. Pengujian ini dilakukan dengan menempatkan spesimen material di antara dua pelat, dan kemudian pelat atas ditekan dengan gaya yang bertambah secara bertahap hingga material mengalami kegagalan atau patah.</p>',
                'sampel' => '2',
                'satuan' => 'Sampel',
                'harga' => 40000,
                'catatan' => 'Minimal 2 sampel (belum termasuk biaya caping)',
                // 'gambar' => '14. Uji tekan material analog.PNG',
                'facility_id' => 3,
                'equipment_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Uji Tarik Baja',
                'slug' => Str::slug('Uji Tarik Baja'),
                'keterangan' => '<p>Uji tarik baja adalah metode pengujian untuk menentukan kekuatan tarik suatu material baja. Uji ini dilakukan dengan memberikan gaya tarik yang sesumbu pada spesimen baja hingga patah, lalu diukur nilai tegangan dan regangan yang terjadi.</p>',
                'sampel' => '2',
                'satuan' => 'Sampel',
                'harga' => 175000,
                'catatan' => 'Minimal 2 sampel (belum termasuk biaya bubut dan las)',
                // 'gambar' => '15. Uji Tarik.jpeg',
                'facility_id' => 3,
                'equipment_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Scan Rebar Beton',
                'slug' => Str::slug('Scan Rebar Beton'),
                'keterangan' => '<p>Scan Rebar Beton atau Rebar Scanning adalah metode uji tanpa rusak (non-destructive testing) yang digunakan untuk mendeteksi dan menganalisa kondisi tulangan baja (rebar) yang berada di dalam beton. Alat ini memungkinkan pengukuran tebal selimut beton, jarak antar tulangan, dan diameter tulangan tanpa perlu membongkar atau merusak struktur beton.</p>',
                'sampel' => '4',
                'satuan' => 'Titik',
                'harga' => 250000,
                'catatan' => 'Minimal 4 titik (belum termasuk biaya survei, transport & akomodasi)',
                // 'gambar' => '16. Uji Scan Rebar.jpeg',
                'facility_id' => 3,
                'equipment_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Berat Jenis Kerikil',
                'slug' => Str::slug('Berat Jenis Kerikil'),
                'keterangan' => '<p>ji berat jenis kerikil adalah pengujian untuk menentukan rasio massa padat kerikil terhadap massa air yang sama volumenya dan suhu yang sama. Uji ini penting untuk mengetahui karakteristik fisik kerikil yang digunakan dalam konstruksi, seperti beton, karena berat jenis mempengaruhi sifat-sifat beton lainnya seperti kekuatan dan kepadatan. </p>',
                'sampel' => '1',
                'satuan' => 'Sampel',
                'harga' => 100000,
                'catatan' => null,
                // 'gambar' => '17. Berat Jenis Kerikil.jpeg',
                'facility_id' => 3,
                'equipment_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Berat Jenis Pasir',
                'slug' => Str::slug('Berat Jenis Pasir'),
                'keterangan' => '<p>Uji berat jenis pasir adalah proses untuk menentukan perbandingan massa pasir terhadap massa air pada volume yang sama. Ini digunakan untuk mengukur densitas pasir dan membantu dalam perhitungan takaran beton, desain struktur, dan berbagai aplikasi konstruksi lainnya.</p>',
                'sampel' => '1',
                'satuan' => 'Sampel',
                'harga' => 100000,
                'catatan' => null,
                // 'gambar' => '18. Uji berat jenis pasir.jpeg',
                'facility_id' => 3,
                'equipment_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Uji Gradasi Kerikil',
                'slug' => Str::slug('Uji Gradasi Kerikil'),
                'keterangan' => '<p>Uji gradasi kerikil, atau uji saringan, adalah metode untuk menentukan distribusi ukuran butiran (grading) dalam campuran kerikil. Uji ini penting karena gradasi kerikil berpengaruh pada karakteristik campuran agregat, seperti kepadatan, porositas, dan workabilitas.</p>',
                'sampel' => '1',
                'satuan' => 'Sampel',
                'harga' => 200000,
                'catatan' => null,
                // 'gambar' => '19,20,39. Gradasi.jpeg',
                'facility_id' => 3,
                'equipment_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Uji Gradasi Pasir',
                'slug' => Str::slug('Uji Gradasi Pasir'),
                'keterangan' => '<p>Uji gradasi pasir adalah proses menentukan distribusi ukuran butir pasir menggunakan saringan dengan lubang-lubang berukuran berbeda. Tujuan utama pengujian ini adalah untuk mengetahui karakteristik pasir dan memastikan bahwa ukuran butir pasir berada dalam rentang yang sesuai untuk tujuan penggunaannya, misalnya dalam pembuatan beton. </p>',
                'sampel' => '1',
                'satuan' => 'Sampel',
                'harga' => 200000,
                'catatan' => null,
                // 'gambar' => '19,20,39. Gradasi.jpeg',
                'facility_id' => 3,
                'equipment_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Uji Kandungan Lumpur Agregat',
                'slug' => Str::slug('Uji Kandungan Lumpur Agregat'),
                'keterangan' => '<p>Uji kandungan lumpur agregat bertujuan untuk menentukan persentase lumpur yang lolos saringan nomor 200 (0,075 mm) dalam agregat halus (pasir) atau agregat kasar (split). Pengujian ini penting karena kandungan lumpur yang tinggi dapat menurunkan kualitas dan kekuatan beton. </p>',
                'sampel' => '1',
                'satuan' => 'Sampel',
                'harga' => 150000,
                'catatan' => null,
                // 'gambar' => '',
                'facility_id' => 3,
                'equipment_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_testing' => 'Uji Abrasi',
                'slug' => Str::slug('Uji Abrasi'),
                'keterangan' => '<p>PenguUji abrasi adalah pengujian untuk menentukan ketahanan suatu bahan terhadap keausan atau kerusakan akibat gesekan atau abrasi. Uji ini sering digunakan untuk mengevaluasi kualitas bahan seperti agregat dalam konstruksi</p>',
                'sampel' => '1',
                'satuan' => 'Sampel',
                'harga' => 250000,
                'catatan' => null,
                // 'gambar' => '22. Uji Abrasi.jpeg',
                'facility_id' => 3,
                'equipment_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // ... (lanjutkan untuk data lainnya dengan pola yang sama) ...
            // Pastikan untuk mengganti 'lab_list_id' menjadi 'facility_id'
            // dan menambahkan 'slug', 'created_at', 'updated_at'
            // serta menghapus 'gambar'

            // Contoh data terakhir dari LSBB
            [
                'nama_testing' => 'Hammer Test',
                'slug' => Str::slug('Hammer Test'),
                'keterangan' => '<p>Hammer test adalah metode pengujian non-destruktif yang digunakan untuk mengevaluasi kekuatan dan mutu beton dengan cara memberikan beban tumbukan (impact) pada permukaan beton. Alat yang digunakan dalam hammer test disebut rebound hammer atau concrete test hammer, dan juga dikenal dengan nama Schmidt Hammer atau Swiss Hammer. Metode ini sangat praktis dan cepat karena dapat digunakan untuk memeriksa mutu beton pada struktur yang sudah jadi, tanpa merusak beton. </p>',
                'sampel' => '10',
                'satuan' => 'Titik',
                'harga' => 100000,
                'catatan' => 'Minimal 10 titik (belum termasuk biaya survei, transport & akomodasi)',
                // 'gambar' => '34. Hammer Test.jpeg',
                'facility_id' => 3,
                'equipment_id' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // LMT - Laboratorium Mekanika Tanah (facility_id: 4)
            [
                'nama_testing' => 'Uji Sondir',
                'slug' => Str::slug('Uji Sondir'),
                'keterangan' => '<p>Uji sondir, juga dikenal sebagai uji penetrasi konus atau Cone Penetration Test (CPT), adalah metode pengujian tanah lapangan yang digunakan untuk mengetahui karakteristik tanah, khususnya daya dukung dan kedalaman lapisan tanah keras. Uji ini dilakukan dengan memasukkan konus ke dalam tanah dan mengukur resistansi yang ditimbulkan.</p>',
                'sampel' => '2',
                'satuan' => 'Titik',
                'harga' => 850000,
                'catatan' => 'Minimal 2 titik (belum termasuk biaya survei, transport & akomodasi)',
                // 'gambar' => '35. Sondir.jpeg',
                'facility_id' => 4,
                'equipment_id' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // ... (lanjutkan untuk data LMT lainnya) ...

            // Contoh data terakhir dari LMT
             [
                'nama_testing' => 'Uji Triaxial CD',
                'slug' => Str::slug('Uji Triaxial CD'),
                'keterangan' => '<p>Pengujian triaxial Consolidated Drained</p>',
                'sampel' => '1',
                'satuan' => 'Sampel',
                'harga' => 500000,
                'catatan' => null,
                // 'gambar' => '',
                'facility_id' => 4,
                'equipment_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // LP - Laboratorium Pemetaan (facility_id: 5)
            [
                'nama_testing' => 'Pemetaan Kontur Tanah',
                'slug' => Str::slug('Pemetaan Kontur Tanah'),
                'keterangan' => '<p>Pemetaan kontur tanah adalah proses visualisasi ketinggian dan bentuk permukaan bumi menggunakan garis-garis kontur. Garis-garis kontur ini menghubungkan titik-titik dengan ketinggian yang sama di atas permukaan bumi. Dengan kata lain, peta kontur memberikan gambaran tentang topografi suatu wilayah. </p>',
                'sampel' => '1',
                'satuan' => 'Ha',
                'harga' => 2000000,
                'catatan' => 'Minimal 1 Ha (belum termasuk biaya survei, transportasi & akomodasi)',
                // 'gambar' => '54-60. Uji pemetaa.jpeg',
                'facility_id' => 5,
                'equipment_id' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // ... (lanjutkan untuk data LP lainnya) ...

            // Contoh data terakhir dari LP
            [
                'nama_testing' => 'Pemetaan Saluran Drainase/Sungai lebar 100 - 300 m',
                'slug' => Str::slug('Pemetaan Saluran Drainase Sungai lebar 100 - 300 m'), // Slug disesuaikan agar unik
                'keterangan' => '<p>Pemetaan saluran/sungai dengan lebar 100-300 meter</p>',
                'sampel' => '1000',
                'satuan' => 'm',
                'harga' => 20000,
                'catatan' => 'Minimal 1 km (belum termasuk biaya survei, transportasi & akomodasi)',
                // 'gambar' => '54-60. Uji pemetaa.jpeg',
                'facility_id' => 5,
                'equipment_id' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
